services:
  pingvin-share:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3333:3000
    volumes:
      - "./data:/pingvin-share/backend/data"
      - "./data/images:/pingvin-share/frontend/public/img"
